### ISSUE TITLE
spike:css-framework

### ISSUE THREAD

**Issue by JessicaDosseh** [interchainberlin/ibc-visualiser#12]
## Choosing our CSS Frameworks

`CSS is how you apply style to your application,` so why use CSS Frameworks? 

> CSS Frameworks are used to save time by pulling in preset styles.

<br/>

- [ ] [Vanilla CSS](#Vanilla-CSS)
- [x] [Component Libraries](#Component-Libraries)
- [ ] [CSS Utility Frameworks](#CSS-Utility-Frameworks)

<br/>
<br/>

### Comparison between CSS Frameworks

---

<br/>

###### Vanilla CSS

<br/>

```
Write your styles and layouts all on your own.  
```

<br/>

| Advantages | Disadvantages | 
| ---------- | ------------- | 
| Full control | Building everything from scratch | 
| No unnecessary code | Danger of  writing  "bad code." | 
| Independent naming conventions |  | 

<br/>

Example: [CSS Tricks](https://css-tricks.com/), [CSS w3schools](https://www.w3schools.com/css/)

<br/>
<br/>

###### Component Libraries 

<br/>

```
Choose from the rich suit of pre-styled components and utility features / classes. 
```

<br/>

| Advantages | Disadvantages | 
| ---------- | ------------- | 
| Rapid development | Little to No control (off the shelf implementation) |
| Follow best practices | Unnecessary overhead code |
| No need to be an expert at styling | "All websites start to look the same" |

<br/>

> Simply add CSS classes to your HTML to get styling writ out of the box.
Disadvantage: we are limited to using what the component library provides. It's true that we can overwrite certain pre-boxed styling with our own CSS code, but if we start overwriting a lot, we could end up in a situation where we might as well use vanilla CSS.  

<br/>

Example: [Material-UI](https://material-ui.com/), [Grommet](https://v2.grommet.io/components)

<br/>
<br/>

###### CSS Utility Frameworks 

<br/>

```
Built your own styles and layouts with the help of utility features and classes.
```

<br/>

| Advantages | Disadvantages | 
| ---------- | ------------- | 
| Rapid development | Lose a medium amount of control |
| Follow best practices | Unnecessary overhead code |
| No need to be an expert at styling | |
| More styling flexibility | |

<br/>

> When it comes to utility libraries, automatic pre-styled components aren't provided; nevertheless, you do get utility classes that add styling functionalities found in component libraries. This allows us the have the flexibility to build our own component styles while also utilizing prepackaged dynamic styling functionalities 
You can think of utility classes as the midway between Vanilla CSS and Component Libraries. 

<br/>

Example: [Tailwind CSS](https://tailwindcss.com/)

<br/>
<br/>

### Let's consider the most important part of our UI 

---

<br/>

```
The Table
```

<br/>

> Define all the functionality we will need exactly, primarily as part of the table, and check what component libraries provide it for us

<br/>
<br/>

###### Material UI

---

| Functionality | Description | 
| ------------- | --- | 
| Providing functionality for tabular data | The [DataGrid component](https://material-ui.com/components/data-grid/) is designed for use-cases that are focused around handling a large amounts of tabular data. While it comes with a more rigid structure, in exchange, you gain more powerful features. <br/><br/> ***MIT version, standard functionality*** <br/> <br/> This is probably the out of the box type of table we need: The Material UI [Commercial data table version](https://material-ui.com/components/data-grid/#commercial-version) <br/> <br/> **[Cost for X license](https://material-ui.com/store/items/material-ui-pro/): $186** | 
| Sorting | Our main initial sorting functionality is Direction & Precedence. Material UI tables naturally come with sort direction. Will the out of the box structure restrict our flexibility from adding other custom sorting methods?  <br/> <br/> `sortDirection={orderBy === headCell.id ? order : false}` |
| Pagination | It's possible to customize the options shown in the "Rows per page" select using the rowsPerPageOptions prop. The ActionsComponent prop of the TablePagination component allows the implementation of custom actions. |
| Handling large amounts of data | Use [react-virtualized](https://github.com/bvaughn/react-virtualized) with the Table component. It renders 200 rows and can easily handle more. Virtualization helps with performance issues. <br/> <br/> `import { AutoSizer, Column, Table } from 'react-virtualized';` |

<br/>
<br/>

###### Tailwind

---

| Functionality | Description | 
| ------------- | --- | 
| Providing functionality for tabular data | I can't say there is much documentation on Tailwind tabular Data. There are just example implementations <br/> <br/> [components example](https://tailwindcomponents.com/components/Tables) <br/> [application-ui](https://tailwindui.com/components/application-ui/lists/tables)  | 
| Sorting | Our main initial sorting functionality is Direction & Precedence. The sorting and pagination functions are custom depending on how you are planning to use the DataTable. <br/> <br/> **This may potentially cause problems in the future as in it may require a lot more time to build from scratch.** |
| Pagination | [application-ui/navigation](https://tailwindui.com/components/application-ui/navigation/pagination) |
| Handling large amounts of data | Not sure |

<br/>
<br/>

### For the [IBC project](https://github.com/interchainberlin/ibc-channel-explorer) Which one should we choose? 

---

```
It may depends on: 
— Your CSS knowledge 
— The time you have 
— The kind of project it is. 
```

<br/>

> For general page layouts I would say choose a CSS Utility Frameworks (i.e., [Tailwind CSS](https://tailwindcss.com/))

<br/>

> **For our tabular data** [Material UI data grid](https://material-ui.com/components/data-grid/) seams like the way to go. 

<br/>

###### My perspective: 
---

>> I understand that we can only choose one because of application bloating, potential performance issues, and developer confusion. ***So I guess Material UI is the answer.*** 

<br/>
<br/>

**Comment by seantking** [comment]
Great write-up. I agree with your assessment. :+1:
