### ISSUE TITLE
UI/UX design

### ISSUE THREAD

**Issue by JessicaDosseh** [interchainberlin/ibc-visualiser#3]
@hxrts , @charleenfei , @seantking : Here is the first UX mockup (no code)

Question: 
Since this design is based on the Cosmos design, would it be possible for us to start a pattern library with all the components and guidelines that cosmos uses for its designs to make it easier to pull from and make things consistent across the board when coding?

**Comment by JessicaDosseh** [comment]
<div align="center">
  <img src="https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FXToN5kIFeA.png?alt=media&token=42dd6b56-4475-44de-ba8d-8d4ad3d093fc" width="100" height="100" />
  
  <hr />
  
  <br/>
  <p> First iteration </p>
  <h3> IBC Explorer Design </h3>
  
  <br/>
    <a href="https://xd.adobe.com/view/ea6bb0af-5d50-4d1f-8a93-d6066e292b16-bf38/"> Visit Mockup </a>
    <br/>
    <a href="https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2F7L1PLPcDjs.mp4?alt=media&token=fd2d0442-1d20-4cae-af82-6edefc7b680a"> Click to watch mockup video </a>
  <br/>
</div>

---

<div align="center">
  <br/>
  <a href="https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2F7L1PLPcDjs.mp4?alt=media&token=fd2d0442-1d20-4cae-af82-6edefc7b680a" title="Link Title"><img src="https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2Fa9CzcY1jbO.png?alt=media&token=4c695c7b-b4c4-49b5-9d76-2eee24638254" alt="preview" /></a>
  
</div>

<br/>



### Design Breakdown 

---

I'm using the [User story Breakdown](https://github.com/interchainberlin/ibc-channel-explorer/issues/1#issuecomment-823395773) as reference. 

<br/>
<br/>

- [ ] External User navigation 

> General functionality for people who want to view information and move on (quick decisions) 

> Priority Table view, add charts and other tables in the future, create a forum for active relayer discussion?, links to docs and repos + FAQ, other analytical functionalities. 

![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FxUm36pNSz1.png?alt=media&token=c38e625b-274e-404b-9e89-1d6a58ef2fbf)


<br/>
<br/>

- [ ] Internal User navigation 

> A space where we can store statistics for grant decisions and PR efforts, access to private information?, more in-depth settings + room for expansion.  

![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FakR4ZmXEKt.png?alt=media&token=bd4f60d1-8502-4daa-9242-697b3e323120)

<br/>
<br/>

- [ ] Table similar to [Map of Zones](https://mapofzones.com/?period=24)

> Note: For the first iteration this section will be really redundant 
 
![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FPfEBlkqaSC.png?alt=media&token=0587ae3a-8b85-4609-be4e-41628054f085)

<br/>
<br/>

- [ ] Meta data similar to [IBC Visualizer](https://github.com/CosmWasm/ibc-visualizer#connection)

> This section is meant to display granular information

![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FrBBs4gHD33.png?alt=media&token=33b3b084-5492-46e5-9aae-24f46c1c9892)

<br/>
<br/>

- [ ] Light and dark mode because why not 

| light | dark |
| ----- | ---- |
| ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FB4_QC2CYPE.png?alt=media&token=8997533a-c926-4da4-86cd-4599bd0e2ef7) | ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2F0qaHiKX_ju.png?alt=media&token=080c7f70-b119-4f76-965a-f1112bfb9de5) |

<br/>
<br/>

**Comment by hxrts** [comment]
this is so cool!!! excited to dig into this on monday :)

**Comment by seantking** [comment]
Great Work!

**Comment by okwme** [comment]
🔥🔥🔥

**Comment by dogemos** [comment]
This is really awesome!

A suggestion I'd add is to set the home screen as an extremely simplified channel explorer interface.

For most users, I think they simply want to know '_what channels are available between `chain-a` and `chain-b`?_'. 

Having a simple Uniswap-like interface where users can choose 'Chain A (source)' and 'Chain B (destination)' and click a button to find which channels are available may be very helpful.

**Comment by JessicaDosseh** [comment]
<div align="center">
  <img src="https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FXToN5kIFeA.png?alt=media&token=42dd6b56-4475-44de-ba8d-8d4ad3d093fc" width="100" height="100" />
  
  <hr />
  
  <br/>
  <p> Iteration # 2 </p>
  <h3> IBC Explorer Design </h3>
  
  <br/>
</div>

<br/>

### Update 

---

> To start, we are stripping it back a little to build out core components.

```
Root Nav 
|── Body component 
          |── Chain Nav 
          |── Chain Name 
          |── Chain Data Table / Chain Meta Data 
```

<br/>

### Sorting 

---

![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FtKeFfHbhTD.png?alt=media&token=006d37da-bb1e-441b-bd16-ce1ff840e23d)

<br/>

> @hxrts  suggested we start with Sort Direction and Sort Precedence for or data.
> > This then brings up a small question, would it be better to use Material UI to do this, or would it be better to create our own component with more flexibility if we will be adding our own sorting methods?

<br/>

1. Sort Direction 

```
Sort Direction is the general sorting functionality to sort from A → Z or from Z → A 
```
![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2Fx2SWfuqWS_.png?alt=media&token=221be684-23e7-4646-a73d-711e427fde1c)

<br/>

2. Sort Precedence

```
Sort Precedence lists all the fields selected to be part of the sorting hierarchy
```
![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FZQ8pX6KI1_.png?alt=media&token=678a149b-07bb-4a8a-bec4-cf31e5db100d)

<br/>


### Routing 

---

> @charleenfei  to make this application dynamic, would we set up the routing to be something like this?  

```
www.url.com/ExplorerType/ChainType

Where 
|──  ExplorerType = Root Nav 
|──  ChainType = Body component 
```
<br/>

So in our case for the IBC explorer it would be: `www.url.com/IBC-Explorer/Gaia-Hub`

<br/>

| ExplorerType | ChainType | 
| ------------- | ----------- |
| Navigate by clicking explorer icon | Navigate by clicking grid menu |
| ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FYzCxa6BQw8.png?alt=media&token=6c107a07-f46d-4b89-9842-af1cf64d5188) | ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2F-i4XNnFzLw.png?alt=media&token=5fc8269d-30a2-4f55-be2e-6dad49ccae83) |

<br/>
<br/>

> If we are going the dynamic navigation, then would we do something like this for the base URL @ `www.url.com/`? 

<br/>

| Stating with IBC Explorer  | Expanding | 
| ------------- | ----------- |
| www.url.com/IBC-Explorer | www.url.com/other-Explorer | 
| ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2Fq0xbFRRPdT.png?alt=media&token=388ef715-ae5c-4047-b4b6-982a4a3fa23c) | ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FypjpAsn8BI.png?alt=media&token=9948b776-5c12-492f-9840-b10ea380ada6) |

<br>

### Body Navigation 

---

<br/>

| Mode | Left Navigation | Top Navigation | 
| ------ | --------------- | --------------- |
| Light | ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FH_AHH_V_n2.png?alt=media&token=fd0761ec-8e2d-4621-80cf-70896d39f5e9) | ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FXlqry2kUMg.png?alt=media&token=f91c1cc1-5b63-4812-91e4-b19b158bea39) | 
| Dark | ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FxqOMDAvl-S.png?alt=media&token=8a628496-7220-4b89-9007-56e4fead71cd) | ![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2Fw--TpKg9Eu.png?alt=media&token=d92a88bc-5825-4950-807d-89e407793bf0) |

<br/>
<br/>

### Why the content in the table is redundant 

---

> The reason why the first table iteration will be redundant is because it will show all the links in one Connection.  

> As in the number of rows per Connection is equivalent to the sum of the deepest data link. 

<br/>

```
Because there are 6 Sequences, there will be 6 repetitive connection rows. 
``` 

![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FC92_PQY3B8.png?alt=media&token=b25475a9-b4f8-4c98-aa42-08c198a1b884)

<br/>

```
Because there are 2 Channels within one Connection with 3 and 2 Sequences in each respectively, 
there will be a total of 5 rows.
```  

![](https://firebasestorage.googleapis.com/v0/b/firescript-577a2.appspot.com/o/imgs%2Fapp%2FJessicaDosseh%2FNTVR8pB67F.png?alt=media&token=82c1ac01-193a-4821-9465-365b8cfda25d)

<br/>

**Comment by charleenfei** [comment]
> cosmos

this is actually a great idea, I'm sorry for not responding to this earlier. Please do this! in the same repo for now though might make sense, until we get an idea of how much this will be used more generically, as i've had the experience of having to update scattered design pattern repos and usually am more pro monorepo.
